-   id: nbcheckorder
    name: Check if notebook cells are sequential
    description: Prevents messy notebooks from being committed.
    entry: nbcheckorder
    language: python
    types: [jupyter]
